FROM node:22-alpine

# Creating the user 'app' so that the project doens't run as root user by default

RUN addgroup app && adduser -S -G app app

# -S Creates a system user
# -G Adds the user to the group we created

  # Here is how it works

   # app (Group)
        # - app (system user)

USER app

WORKDIR /app

COPY package*.json ./
 
# " package*.json: " This specifies which files to copy. 
# In this case, it's copying all files that start with package and end with .json. 
# This usually includes package.json and potentially package-lock.json if it exists.

USER root

# Think of it as changing the account you're using on a computer. 
# If you were previously using a standard user account (app), 
# switching to root gives you full administrative privileges inside the container. 
# This might be done to perform tasks that require higher permissions, like installing 
# system packages or modifying system configurations.

RUN chown -R app:app .

# So, RUN chown -R app:app . changes the ownership of the current directory and everything 
# in it to the user and group named app. 
# This is often done to ensure that the user running the application inside the container 
# has the correct permissions to access and modify files.

USER app

# Changes the root user access back to the system user

RUN npm install

COPY . .

EXPOSE 5173

CMD npm run dev

